<?php

declare(strict_types=1);

namespace App\Notifications\AI;

use App\Enums\AlertSeverity;
use App\Models\Tenant\AiAlert;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Notifications\Messages\MailMessage;
use Illuminate\Notifications\Notification;

class AiAlertNotification extends Notification implements ShouldQueue
{
    use Queueable;

    public function __construct(
        public AiAlert $alert
    ) {}

    /**
     * @return array<int, string>
     */
    public function via(object $notifiable): array
    {
        return ['mail', 'database'];
    }

    public function toMail(object $notifiable): MailMessage
    {
        $mail = (new MailMessage)
            ->subject($this->getSubject())
            ->greeting("Hello {$notifiable->name}!");

        // Add visual urgency for critical/high severity
        if ($this->alert->severity === AlertSeverity::Critical) {
            $mail->error();
        }

        $mail->line("**Alert Type:** {$this->alert->alert_type->label()}")
            ->line("**Severity:** {$this->alert->severity->label()}")
            ->line('')
            ->line($this->alert->description);

        // Add entity name if available
        $entityName = $this->alert->relatedEntityName;
        if ($entityName) {
            $mail->line('')
                ->line("**Related Entity:** {$entityName}");
        }

        // Add action button based on alert type
        $actionUrl = $this->getActionUrl();
        $actionText = $this->getActionText();

        return $mail
            ->line('')
            ->action($actionText, $actionUrl)
            ->line('This alert was generated by the AI insights system.');
    }

    /**
     * @return array<string, mixed>
     */
    public function toArray(object $notifiable): array
    {
        return [
            'type' => 'ai_alert',
            'alert_id' => $this->alert->id,
            'alert_type' => $this->alert->alert_type->value,
            'severity' => $this->alert->severity->value,
            'title' => $this->alert->title,
            'description' => $this->alert->description,
            'branch_id' => $this->alert->branch_id,
            'alertable_type' => $this->alert->alertable_type,
            'alertable_id' => $this->alert->alertable_id,
            'entity_name' => $this->alert->relatedEntityName,
            'requires_immediate_attention' => $this->alert->requiresImmediateAttention(),
        ];
    }

    protected function getSubject(): string
    {
        $severityPrefix = match ($this->alert->severity) {
            AlertSeverity::Critical => '[CRITICAL] ',
            AlertSeverity::High => '[HIGH] ',
            default => '',
        };

        return "{$severityPrefix}{$this->alert->title}";
    }

    protected function getActionUrl(): string
    {
        $branchId = $this->alert->branch_id;

        return match ($this->alert->alertable_type) {
            'App\Models\Tenant\Member' => url("/branches/{$branchId}/members/{$this->alert->alertable_id}"),
            'App\Models\Tenant\Cluster' => url("/branches/{$branchId}/clusters/{$this->alert->alertable_id}"),
            'App\Models\Tenant\Household' => url("/branches/{$branchId}/households/{$this->alert->alertable_id}"),
            'App\Models\Tenant\PrayerRequest' => url("/branches/{$branchId}/prayer-requests/{$this->alert->alertable_id}"),
            default => url("/branches/{$branchId}/ai-insights"),
        };
    }

    protected function getActionText(): string
    {
        return match ($this->alert->alertable_type) {
            'App\Models\Tenant\Member' => 'View Member',
            'App\Models\Tenant\Cluster' => 'View Cluster',
            'App\Models\Tenant\Household' => 'View Household',
            'App\Models\Tenant\PrayerRequest' => 'View Prayer Request',
            default => 'View AI Insights',
        };
    }
}
