<?php

declare(strict_types=1);

namespace App\Notifications;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Notifications\Messages\MailMessage;
use Illuminate\Notifications\Notification;

class MemberLifecycleTransitionNotification extends Notification implements ShouldQueue
{
    use Queueable;

    /**
     * @param  array<array{member_id: string, member_name: string, from_stage: ?string, to_stage: string}>  $transitions
     */
    public function __construct(
        public array $transitions,
        public string $branchId
    ) {}

    /**
     * @return array<int, string>
     */
    public function via(object $notifiable): array
    {
        return ['mail', 'database'];
    }

    public function toMail(object $notifiable): MailMessage
    {
        $count = count($this->transitions);
        $subject = $count === 1
            ? 'Member Lifecycle Alert: 1 member needs attention'
            : "Member Lifecycle Alert: {$count} members need attention";

        $mail = (new MailMessage)
            ->subject($subject)
            ->greeting("Hello {$notifiable->name}!")
            ->line('The following members have transitioned to concerning lifecycle stages and may need pastoral attention:')
            ->line('');

        foreach ($this->transitions as $transition) {
            $fromStage = $transition['from_stage'] ? $this->formatStage($transition['from_stage']) : 'Unknown';
            $toStage = $this->formatStage($transition['to_stage']);

            $mail->line("• **{$transition['member_name']}**: {$fromStage} → {$toStage}");
        }

        return $mail
            ->line('')
            ->line('These members may be experiencing challenges or reduced engagement. Consider reaching out to offer support.')
            ->action('View Members', url("/branches/{$this->branchId}/members"))
            ->line('This notification was generated by the AI-powered lifecycle detection system.');
    }

    /**
     * @return array<string, mixed>
     */
    public function toArray(object $notifiable): array
    {
        return [
            'type' => 'member_lifecycle_transition',
            'branch_id' => $this->branchId,
            'transitions' => $this->transitions,
            'count' => count($this->transitions),
            'message' => $this->getSummaryMessage(),
        ];
    }

    protected function formatStage(string $stage): string
    {
        return match ($stage) {
            'prospect' => 'Prospect',
            'new_member' => 'New Member',
            'growing' => 'Growing',
            'engaged' => 'Engaged',
            'disengaging' => 'Disengaging',
            'at_risk' => 'At Risk',
            'dormant' => 'Dormant',
            'inactive' => 'Inactive',
            default => ucfirst(str_replace('_', ' ', $stage)),
        };
    }

    protected function getSummaryMessage(): string
    {
        $count = count($this->transitions);

        if ($count === 1) {
            $member = $this->transitions[0];
            $toStage = $this->formatStage($member['to_stage']);

            return "{$member['member_name']} has transitioned to {$toStage} and may need attention.";
        }

        return "{$count} members have transitioned to concerning lifecycle stages and may need attention.";
    }
}
